landing_page/landing_page/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('one_page.urls'), name='home_page'),
    path('admin/', admin.site.urls),
]

# custom error handling
handler404 = 'one_page.views.custom_page_not_found_view'
handler500 = 'one_page.views.custom_error_view'
handler403 = 'one_page.views.custom_permission_denied_view'
handler400 = 'one_page.views.custom_bad_request_view'

# custom admin page
admin.site.site_header = "My Landing Page Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to Your Site Admin Portal"

landing_page/one_page/urls.py
from django.urls import path
from . import views

app_name = 'one_page'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('about/', views.AboutPage.as_view(), name='about_page'),
]

landing_page/one_page/models.py
from django.db import models
from django.core.validators import validate_email

# Create your models here.
class ContactDatabase(models.Model):
    objects = models.Manager() # this is needed to avoid VS Code error
    email = models.EmailField(max_length=100, validators=[validate_email])
    
    def __str__(self):
        return str(self.email)

landing_page/one_page/forms.py
from django import forms
from django.forms import ModelForm
from .models import ContactDatabase

class ContactForm(ModelForm):
    """User can leave a mail to be included in the waiting list"""
    class Meta:
        model = ContactDatabase
        fields = "__all__"
        
        # add here your custom labels for the forms
        labels = {
            'email': 'Please insert your email'
        }
        
        widgets = {
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
        }
                

landing_page/one_page/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView

from .forms import ContactForm
from .models import ContactDatabase

# home page
class HomePage(TemplateView):
    """Manage home page and forms"""
    template_name = 'landing_page/home_page.html'
    
    def get(self, request, *args, **kwargs):
        form = ContactForm()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request, *args, **kwargs):
        """Manage form submission"""
        form = ContactForm(request.POST)
        if form.is_valid():
            if ContactDatabase.objects.filter(email=form.cleaned_data['email']).count() < 1:
                print(form.cleaned_data)
                form.save()
                message = 'Thanks for your interest!'
            else:
                message = 'Warning! Email already exists'
        else:
            message = 'Insert a valid email!'
        
        return render(request, self.template_name, {'form': form, 'warning': message})
        
# about page
class AboutPage(TemplateView):
    template_name = 'landing_page/about_page.html'
    
# custom error handling

# 404 page
def custom_page_not_found_view(request, exception=None):
    return render(request, "landing_page/errors/404.html", status=404)

# 500 page
def custom_error_view(request, exception=None):
    return render(request, "landing_page/errors/500.html", status=500)

# 403 page
def custom_permission_denied_view(request, exception=None):
    return render(request, "landing_page/errors/403.html", status=403)

# 400 page
def custom_bad_request_view(request, exception=None):
    return render(request, "landing_page/errors/400.html", status=400)

landing_page/templates/landing_page/about_page.html
{% extends 'landing_page/base.html' %}
{% load static %}

{% block title %} 

<title>Home Page</title> 

{% endblock %}

{%block navbar %}

<a class="nav-link" aria-current="page" href="{% url 'one_page:home_page' %}">Home</a>
<!-- <a class="nav-link" href="#">Features</a> -->
<a class="nav-link active" href="{% url 'one_page:about_page' %}">About us</a>

{% endblock %}

    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-4 d-flex flex-column">
                    <img class="rounded-circle align-self-center" src="{% static 'landing_page/img/profile1.jpg' %}" alt="Profile Image" width="140" height="140">
                    <h2>CEO</h2>
                    <p>Wannabe introvert. Incurable zombie lover. Tv guru. Passionate coffeeaholic. Total music.</p>
                    <p class="mt-auto">
                        <a class="btn btn-primary center-bottom" href="#" role="button">Linkedin &raquo;</a>
                    </p>
                </div>
                <div class="col-md-4 d-flex flex-column">
                    <img class="rounded-circle align-self-center" src="{% static 'landing_page/img/profile2.jpg' %}" alt="Profile Image" width="140" height="140">
                    <h2>CTO</h2>
                    <p>Infuriatingly humble bacon fanatic. Prone to fits of apathy. Gamer. Passionate student. Dog lover.</p>
                    <p class="mt-auto">
                        <a class="btn btn-primary" href="#" role="button">Linkedin &raquo;</a>
                    </p>
                </div>
                <div class="col-md-4 d-flex flex-column">
                    <img class="rounded-circle align-self-center" src="{% static 'landing_page/img/profile3.jpg' %}" alt="Profile Image" width="140" height="140">
                    <h2>CMO</h2>
                    <p>Friend of animals everywhere. Future teen idol. General internet junkie. Evil webaholic. Extreme reader. Gamer.</p>
                    <p class="mt-auto">
                        <a class="btn btn-primary" href="#" role="button">Email &raquo;</a>
                    </p>
                </div>
            </div>
        </div>
    {% endblock %}

landing_page/templates/landing_page/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <!-- Django Boilerplate, an open source project made by Carlo Occhiena -->

    {% block title%}
    
    <title>Home Page</title>
    
    {% endblock %}

    <!-- FAVICON -->
    <link rel="icon" href="{% static 'landing_page/img/favicon.jpg' %}">

    <!-- BOOTSTRAP CSS  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <link href="https://getbootstrap.com/docs/5.0/examples/cover/cover.css" rel="stylesheet">

    <!-- In-Page Styling -->
    <style>

        body::after {
            content: "";
            background-image: url("{% static 'landing_page/img/hp_background.jpg' %}");
            opacity: 0.5;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            position: absolute;
            z-index: -1;   
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }
        }

    </style>

</head>
  
<body class="d-flex h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
        <div>
            <img class="float-md-start mb-0 my-auto" src="{% static 'landing_page/img/logo.png' %}" alt="company_logo" width="45px" height="45px">
            <h2 class="float-md-start mb-0">Company Name</h2>
            <nav class="nav nav-masthead justify-content-center float-md-end">
            
            {%block navbar %}
            
            <a class="nav-link active" aria-current="page" href="{% url 'one_page:home_page' %}">Home</a>
            <!-- <a class="nav-link" href="#">Features</a> -->
            <a class="nav-link" href="{% url 'one_page:about_page' %}">About us</a>
            
            {% endblock %}
            
            </nav>
        </div>
    </header>

    <!-- Above the block --> 
    {% block content %}  
        

    {% endblock %}
    <!-- Below the block -->

        <footer class="mt-auto text-white-50">
            <p>Made with love and <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://github.com/carloocchiena" class="text-white">Carlo</a>.</p>
        </footer>

    </div>
    
  </body>
</html>

landing_page/templates/landing_page/home_page.html
{% extends 'landing_page/base.html' %}
{% load static %}

{% block title %} 

<title>Home Page</title> 

{% endblock %}

{%block navbar %}

<a class="nav-link active" aria-current="page" href="{% url 'one_page:home_page' %}">Home</a>
<!-- <a class="nav-link" href="#">Features</a> -->
<a class="nav-link" href="{% url 'one_page:about_page' %}">About us</a>

{% endblock %}

    {% block content %}
    
    <main class="px-3" >
        
        <h1>Our Product</h1>
        <h1>will be ready soon.</h1>
        
        <p class="lead">
            Insert here a clever marketing message to encourage people to leave their mail to stay updated with the
            go-live of your product.
        </p>

        
        <form action="" method="post">
            <div class="form-group">  
                {% csrf_token %}
                {% for field in form %}
                    <div class="lead form-group">
                        <label for=""> {{ field.label }} </label>
                    </div>
                    <br>
                    <div class="input-group">
                        <div class="form-group mx-auto mb-4">
                            <input
                                class="form-control"
                                type="{{ field.type }}"
                                id="{{ field.auto_id }}"
                                name="{{ field.html_name }}"
                                class="form-control"
                                maxlength="{{ field.max_length }}"
                                id="{{ field.id_for_label }}"
                                placeholder="&#9993; your_mail@email.com"
                                required
                            />
                            <!--<br><small id="emailHelp" class="form-text text-muted">We hate spam as much as you do.</small>-->          
                        </div>
                    </div>
                {% endfor %}
                <div class="row checkbox-row">
                    <div class="col-xs-2 col-xs-offset-4">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                        <label class="form-check-label" for="exampleCheck1">Flag the privacy consent</label>
                    </div>
                </div>
                <br>
                <button class="btn btn-lg btn-secondary fw-bold border-white bg-white" type="submit">Submit</button>
            </div> 
        </form>
        <br>
        {{ warning }}

    </main>
    
    {% endblock %}