social/social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('twtr.urls')),
    path('admin/', admin.site.urls),
]

# custom error handling
handler404 = 'twtr.views.custom_page_not_found_view'
handler500 = 'twtr.views.custom_error_view'
handler403 = 'twtr.views.custom_permission_denied_view'
handler400 = 'twtr.views.custom_bad_request_view'

# custom admin page
admin.site.site_header = "TWTR Admin Page"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to TWTR Admin Portal"

social/twtr/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import dashboard, profile_list, profile, register

app_name = 'twtr'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('profile_list/', profile_list, name='profile_list'),
    path('profile/<int:pk>', profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='twtr/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='twtr/logout.html'), name='logout'),
    path('register/', register, name='register'),
    # path('accounts/', include('django.contrib.auth.urls')), # default django auth urls you may abilitate
]

social/twtr/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    """Model to handle user and who they follow"""
    objects = models.Manager() # this is needed to avoid VS Code error
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self", related_name="followed_by", symmetrical=False, blank=True
    )

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()
        
class Twt(models.Model):
    user = models.ForeignKey(User, related_name='twts', on_delete=models.DO_NOTHING)
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return (f'{self.user} '
                f'{self.created_at:%Y-%m-%d %H:%M}: '
                f'{self.body[:15]}...'
                )
        

social/twtr/forms.py
from django import forms
from .models import Twt

class TwtForm(forms.ModelForm):
    """Manage input with a form field in dashboard"""
    body = forms.CharField(required=True, 
                           widget=forms.widgets.Textarea(
                               attrs={'placeholder': 'What\'s happening?',
                                      'class':'textarea is-info is-medium'}),
                           label='',
                           )
    
    class Meta:
        model = Twt
        exclude = ('user',)
        

social/twtr/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from .forms import TwtForm
from .models import Twt, Profile

# Main dashboard
@login_required
def dashboard(request):
    """Manage interactions within the dashboard"""
    form = TwtForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            twt = form.save(commit=False)
            twt.user = request.user
            twt.save()
            return redirect('twtr:dashboard')
    
    followed_twts = Twt.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    )
        
    return render(request, 'twtr/dashboard.html', {'form': form, 'twts': followed_twts})

# Registration function for new users
def register(request):
    """Manage user registration"""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('twtr:dashboard')
    
    else:
        form = UserCreationForm()
    return render(request, 'twtr/register.html', {'form': form})

# List all the profiles
@login_required
def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, 'twtr/profile_list.html', {'profiles': profiles})

# Display the single user detail page
@login_required
def profile(request, pk):
    """Manage user profile, follows and unfollows"""
    profile = Profile.objects.get(pk=pk)
    if request.method == 'POST':
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get('follow')
        if action == 'follow':
            current_user_profile.follows.add(profile)
        elif action == 'unfollow':
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, 'twtr/profile.html', {'profile': profile})

# custom error handling

# 404 page
def custom_page_not_found_view(request, exception=None):
    return render(request, "twtr/errors/404.html", status=404)

# 500 page
def custom_error_view(request, exception=None):
    return render(request, "twtr/errors/500.html", status=500)

# 403 page
def custom_permission_denied_view(request, exception=None):
    return render(request, "twtr/errors/403.html", status=403)

# 400 page
def custom_bad_request_view(request, exception=None):
    return render(request, "twtr/errors/400.html", status=400)

social/twtr/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Django Boilerplate, an open source project made by Carlo Occhiena -->

    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

    <!-- FAVICON -->
    <link rel="icon" href="{% static 'twtr/img/favicon.png' %}">

    <title>TWTR</title>
</head>
<body>
    <a href="{% url 'twtr:dashboard' %} ">
        <section class="hero is-small is-info mb-4">
            <div class="hero-body">
                <h1 class="title is-1">
                    TWTR
                </h1>
                <p class="subtitle is-4">
                    Your Twitter tribute, build with Django
                </p>
            </div>
        </section>
    </a>
    
    <div class="container">
        <div class="columns">
            {% block content %}

            {% endblock content %}
        </div>
    </div>

</body>
</html>

social/twtr/templates/twtr/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    {% for twt in twts %}
        <div class="box">
            {{ twt.body }}
            <span class="is-small has-text-grey-light">
                {{ twt.created_at }} 
                by 
                <a href="{% url 'twtr:profile' twt.user.profile.id %}">
                    {{ twt.user.username }}
                </a>
            </span>
        </div>
    {% endfor %}
</div>

<div class="column is-one-third">
   
    <div class="block">
        <a href="{% url 'twtr:profile_list' %}">
            <button class="button is-info is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block"> 
        <a href="{% url 'twtr:profile' request.user.profile.id %}">
            <button class="button is-info is-light is outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>

    <div class="block">
        <div class="block">
            <h2 class="title is-2">Add a twt</h2>
        </div>
        <div class="block">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-info is-fullwidth is-medium mt-5" type="submit">Twt it!</button>
            </form>
        </div>
    </div>
        <href class="button is-info is-light is outlined is-fullwidth">
            <a href="{% url 'twtr:logout' %}">Logout</a>
</div>

{% endblock content %}

social/twtr/templates/twtr/login.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    <h2 class="title is-2">Welcome to TWTR</h2>
    <h3 class="title is-3">It's happening now</h3>
    <p>Jump abord!</p>
    <p>
        New user?
        <a href="{% url 'twtr:register' %}">Create a free account!</a>
    </p>
</div>

<div class="column is-one-third">
    <div class="block">
      <h3 class="title is-3">Login</h3>
    </div>
    
    <div class="block">
        <form method="post" action="{% url 'twtr:login' %}">
            <div class="field">
                {% csrf_token %}
                <label class="label">Username</label>
                <div class="control has-icons-left">
                    <input
                    class="input"  
                    type="text"
                    id="id_username"
                    name="username" 
                    placeholder="Your username"
                    maxlength="20" 
                    required
                    />
                    <span class="icon is-small is-left">
                        <i class="fa fa-envelope"></i>
                    </span>
                </div>
            </div>

            <div class="field">
                <label class="label">Password</label>
                <div class="control has-icons-left">
                    <input
                    class="input"  
                    type="password" 
                    id="id_password"
                    name="password"
                    placeholder="*******" 
                    required
                    />
                    <span class="icon is-small is-left">
                        <i class="fa fa-lock"></i>
                    </span>
                </div>
            </div>
      
            {% if form.non_field_errors %} 
            
                {% for error in form.non_field_errors %}
                    <p style="font-size: 13px;">
                        {{ error|escape }}
                    </p><br>
                {% endfor %} 
            
            {% endif %}
      
            <button type="submit" class="button is-info is-fullwidth">Login</button>
      </form>
    </div>
</div>

{% endblock content %}

social/twtr/templates/twtr/profile.html
{% extends "base.html" %}

{% block content %}

<div class="column">

    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s twtr
    </h1>
    </div>

    <form method="POST">
        {% csrf_token %}
        <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
                <!--  <button class="button is-info is-static">Follow</button>  -->
                <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
            {% else %}
                <button class="button is-info" name="follow" value="follow">Follow</button>
                <!-- <button class="button is-info is-static">Unfollow</button> -->
            {% endif %}
        </div>
    </form>

    <div class="content">
        {% for twt in profile.user.twts.all %}
            <div class="box">
                {{ twt.body }}
                <span class="is-small has-text-grey-light">
                    {{ twt.created_at }}
                </span>
            </div>
        {% endfor %}
    </div>

</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'twtr:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        {% if profile.user.username == user.username %}
            <a href="{% url 'twtr:logout' %}" class="button is-info is-light is outlined is-fullwidth">
                Logout
            </a>
        {% endif %}
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'twtr:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'twtr:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

social/twtr/templates/twtr/profile_list.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
        <div class="card">
            <a href="{% url 'twtr:profile' profile.id %}">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img class=is-rounded src=https://banner2.cleanpng.com/20180426/tre/kisspng-memoji-pile-of-poo-emoji-sticker-smiley-user-avatars-5ae24b69cf6571.6662156015247798818495.jpg 
                                alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">
                                {{ profile.user.username}}
                            </p>
                            <p class="subtitle is-6">
                                @{{ profile.user.username|lower }}
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

{% endfor %}

</div>
   
{% endblock content %}

social/twtr/templates/twtr/register.html
{% extends 'base.html' %} 

{% block content %}

<div class="column">
    <h2 class="title is-2">Jump into TWTR in 1,5 minutes!</h2>
    <h3 class="title is-3">Create a free account</h3>
</div>

<div class="column is-one-third">
    <div class="block">
        <form method="post" action="{% url 'twtr:register' %}">
            {% csrf_token %} 
            {% for field in form %}
                <div class="field">
                    <div class="form-group">
                        <label class="label">{{ field.label_tag }} </label>
                        <div class="control has-icons-left">
                            <input
                                class="input"
                                type="{% if 'password' in field.label_tag %}password{% else %}text{% endif %}"
                                id="{{ field.auto_id }}"
                                name="{{ field.html_name }}"
                                class="form-control"
                                maxlength="{% if 'username' in field.label_tag %}20{% endif %}"
                                id="{{ field.id_for_label }}"
                                required
                            />
                            <span class="icon is-small is-left">
                                <i class="{% if 'password' in field.label_tag %}fa fa-lock{% else %}fa fa-envelope{% endif %}"></i>
                            </span>
                        </div>
                    </div>
                </div>

                    {% if field.errors %} 
                        {% for error in field.errors %}
                            <p style="font-size: 13px;">
                                {{ error|escape }}
                            </p><br>
                        {% endfor %} 
                    {% endif %} 
            {% endfor %}
                    <button type="submit" class="button is-info is-fullwidth">Register</button>
                
        </form>
    </div>
</div>

{% endblock %}